server.port=8080
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;NON_KEYWORDS=KEY,VALUE,USER
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.session.store-type=none
spring.session.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=none

# Dummy OAuth2 and SAML2 properties to allow Spring Security to initialize
spring.security.oauth2.client.registration.test.client-id=test
spring.security.oauth2.client.registration.test.client-secret=test
spring.security.oauth2.client.provider.test.authorization-uri=http://localhost:8080/auth
spring.security.oauth2.client.provider.test.token-uri=http://localhost:8080/token

spring.security.saml2.relyingparty.registration.test.entity-id=test
spring.security.saml2.relyingparty.registration.test.assertingparty.entity-id=test
spring.security.saml2.relyingparty.registration.test.assertingparty.sso.url=http://localhost:8080/sso
spring.security.oauth2.client.registration.test.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.test.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.saml2.relyingparty.registration.test.assertingparty.single-sign-on.url=http://localhost:8080/sso
spring.security.saml2.relyingparty.registration.test.assertingparty.single-sign-on.binding=REDIRECT
spring.security.saml2.relyingparty.registration.test.assertingparty.single-sign-on.sign-request=false
management.health.ldap.enabled=false
hibernate.cache.region.factory_class=org.hibernate.cache.internal.NoCachingRegionFactory
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.internal.NoCachingRegionFactory
