catalina.home=/tmp
dbType=postgres
dbUser=clinica
dbPass=clinica
db=clinica
dbPort=5432
dbHost=localhost
sysURL=http://localhost:8080/OpenClinica/MainMenu
ldap.enabled=false
ldap.host=ldap://localhost:389
ldap.userDn=cn=admin,dc=localhost
ldap.password=localhost
ldap.loginQuery=(sAMAccountName={0})
ldap.passwordRecoveryURL=http://www.google.com
ldap.userSearch.baseDn=dc=localhost
ldap.userSearch.query=(&(memberOf=CN=ldapgroup,OU=ldap,dc=localhost)(|(sAMAccountName=*{0}*)))
ldap.userData.distinguishedName=distinguishedName
ldap.userData.username=sAMAccountName
ldap.userData.firstName=givenName
ldap.userData.lastName=sn
ldap.userData.email=mail
ldap.userData.organization=company
mailHost=localhost
mailPort=25
mailProtocol=smtp
mailUsername=test
mailPassword=test
mailSmtpAuth=false
mailSmtpStarttls.enable=false
mailSmtpsAuth=false
mailSmtpsStarttls.enable=false
mailSmtpConnectionTimeout=1000
ruleDesignerURL=http://localhost


# Base URL for external help documentation
help.base.url=https://docs.openclinica.com

# Enable/disable internal randomization module
randomization.enabled=false

