CREATE TABLE IF NOT EXISTS SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS clinical_records (
    id VARCHAR(255) PRIMARY KEY,
    study_oid VARCHAR(255),
    subject_oid VARCHAR(255),
    data TEXT
);

CREATE TABLE IF NOT EXISTS dde_records (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255),
    study_id INT,
    subject_oid VARCHAR(255),
    item_oid VARCHAR(255),
    first_value VARCHAR(255),
    submission_count INT
);

CREATE UNIQUE INDEX IF NOT EXISTS dde_records_unique_idx ON dde_records (tenant_id, study_id, subject_oid, item_oid);

CREATE TABLE IF NOT EXISTS configuration_drafts (
    id VARCHAR(36) PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    draft_type VARCHAR(50) NOT NULL,
    draft_data TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    expires_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log_event_type (
    audit_log_event_type_id SERIAL PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS audit_log_event (
    audit_id SERIAL PRIMARY KEY,
    audit_date TIMESTAMP,
    audit_table VARCHAR(500),
    user_id INT,
    entity_id INT,
    entity_name VARCHAR(500),
    reason_for_change VARCHAR(1000),
    audit_log_event_type_id INT,
    old_value VARCHAR(4000),
    new_value VARCHAR(4000),
    event_crf_id INT,
    study_event_id INT,
    event_crf_version_id INT
);

